site_name: Документация API
description: Тест MkDocs Material
nav:
  - Обзор API: index.md
  - Руководство: start.md
  - Справочник: manual.md
  - Swagger: dist/index.html
theme:
  name: material
  language: ru